### ISSUE TITLE
Add Github secrets

### ISSUE THREAD

**Issue by Nyholm** [psalm/psalm-github-actions#15]
We need to add these secrets: DOCKER_USERNAME and DOCKER_PASSWORD 

Currently the "watch" build fails: https://github.com/psalm/psalm-github-actions/runs/1149379803?check_suite_focus=true

Related to #13

**Comment by Nyholm** [comment]
Btw, Secrets are safe, They will not be available on PRs.

**Comment by muglug** [comment]
Done, sorry that took a while - hectic week

**Comment by Nyholm** [comment]
No worries, Everything is working now and all should be automatic from now on. 

I'll double check the next few releases from Psalm.
