### ISSUE TITLE
Security Analysis step errors out

### ISSUE THREAD

**Issue by LukasReschke** [psalm/psalm-github-actions#20]
https://github.com/LukasReschke/server/blob/7f481bb96ba8fe1a3c5c13ca4944b7da9be2be01/.github/workflows/psalm-security.yml#L1-L26

This fails at https://github.com/LukasReschke/server/runs/1414709810:

```
Error: Detected tainted text
Error: Detected tainted code passed to include or similar
Error: Detected tainted shell code
Error: Detected tainted shell code
Error: Detected tainted shell code
Error: Detected tainted shell code
Error: Detected tainted shell code
Error: Detected tainted text
Error: Detected tainted text
Error: Detected tainted text
Error: Detected tainted text
Error: Detected tainted shell code
Error: Detected tainted shell code
Error: Detected tainted shell code
```

![image](https://user-images.githubusercontent.com/878997/99451518-9b88e900-2922-11eb-83ce-06a58c6fda51.png)

And thus doesn't result in the files being uploaded to GitHub as the step is skipped.

**Comment by LukasReschke** [comment]
@muglug - is this possible because of `--output-format=github`?

https://github.com/psalm/psalm-github-actions/blob/0b419a6765b0d6325bded2c8d7539c2bb3395dd9/entrypoint.sh#L30

**Comment by LukasReschke** [comment]
I guess https://github.com/vimeo/psalm/blob/24a38f21cecd4049f3445bb984c09a19d674d360/src/Psalm/Report/GithubActionsReport.php#L16 should return `warning` instead of `error` for taint flow scanning?

https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-a-warning-message

**Comment by LukasReschke** [comment]
Alternatively, the following works but isn't really great ;-)

```diff
jobs:
  psalm:
    name: Psalm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Psalm
        uses: docker://vimeo/psalm-github-actions
+       continue-on-error: true
        with:
          security_analysis: true
          report_file: results.sarif
      - name: Upload Security Analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: results.sarif
```

**Comment by muglug** [comment]
Fixed with this slight hack: https://github.com/vimeo/psalm/commit/6e39c24a1744ce343c5a175fd1b43de3bd1b42ef
