### ISSUE TITLE
Update to use PHP 8

### ISSUE THREAD

**Issue by seb-jean** [psalm/psalm-github-actions#31]
Hello,

Is there a possibility to update the Dockerfile for PHP 8?

Thanks :)

**Comment by morozov** [comment]
FWIW, JetBrains PhpStorm stubs [require PHP 8](https://github.com/JetBrains/phpstorm-stubs/blob/v2021.1/composer.json#L17) and use [multi-line annotations](https://github.com/JetBrains/phpstorm-stubs/blob/v2021.1/Core/Core.php#L1097-L1102) which cannot be parsed by PHP 7. This makes the image based on PHP 7 effectively incompatible with the newest stubs.

**Comment by simPod** [comment]
My lib requires PHP8+ and this image is incompatible with it. We should at least have multiple versions of this image available like `vimeo/psalm-github-actions:4.10.0-php74` + `vimeo/psalm-github-actions:4.10.0-php80` or sth like that

**Comment by skjnldsv** [comment]
https://github.com/psalm/psalm-github-actions/pull/43

**Comment by orklah** [comment]
Fixed by #43
