### ISSUE TITLE
Trigger daily updates on docker

### ISSUE THREAD

**Issue by Nyholm** [psalm/psalm-github-actions#4]
We need to build this image on Docker daily. Currently the last build was 3 months ago. That means that we are running an outdated version of Psalm. 

One way to solve this issue is to use github action to build periodically and do a CURL request to trigger a dockerhub build.

**Comment by muglug** [comment]
Could you PR this?

**Comment by Nyholm** [comment]
Sure, but I need help with the URL. 

Let's discuss that on the PR.
